@startuml
hide circle
skinparam classAttributeIconSize 0

Class "  <<interface>>  \nParser" as Parser<AddCommand>
Class AddCommandParser

Class AddCommand
Class CommandResult

Class ArgumentMultimap
Class ParserUtil

Class Student
Class Name
Class Id
Class Major
Class Intake
Class Phone
Class Email
Class Address
Class Tag

AddCommandParser .up.|> Parser

AddCommandParser .down.> AddCommand: initialize >
AddCommandParser .right.> ArgumentMultimap: utilizes >
AddCommandParser .right.> ParserUtil: utilizes >

AddCommand .down.> CommandResult: outputs >

AddCommand -right-> Student: adds >

Student -down-> Name: has >
Student -down-> Id: has >
Student -down-> Phone: has >
Student -down-> Email: has >
Student -down-> Address: has >
Student -down-> Intake: has >
Student -down-> Major: has >
Student -down-> Tag: has >

@enduml
