@startuml
!include ../style.puml
skinparam ArrowFontStyle plain

box Logic LOGIC_COLOR_T1
participant ": LogicManager" as logicManager LOGIC_COLOR
participant ": AddressBookParser" as addressBookParser LOGIC_COLOR
participant ": UndoCommandParser" as UndoCommandParser LOGIC_COLOR
participant ": UndoCommand" as UndoCommand LOGIC_COLOR
participant ": CommandResult" as commandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant "m: Model" as model MODEL_COLOR
end box

[-> logicManager : execute("undo")
activate logicManager

logicManager -> addressBookParser : parseCommand("undo")
activate addressBookParser

create UndoCommandParser
addressBookParser -> UndoCommandParser
activate UndoCommandParser

addressBookParser -> UndoCommandParser : parse("")

create UndoCommand
UndoCommandParser -> UndoCommand
activate UndoCommand
returnCommand

return Command


return Command
destroy UndoCommandParser
logicManager -> UndoCommand : execute(m)
activate UndoCommand
UndoCommand -> model : resetToPreviousState()
activate model
return

|||

create commandResult
UndoCommand -> commandResult
activate commandResult
return commandResult

return commandResult

@enduml
